# Generated by Django 4.2.2 on 2023-06-27 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_like_active_alter_follower_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user_likes",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
