# Generated by Django 4.2.2 on 2023-06-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_watchlistitem_active_watchlistitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
